<?php
declare(strict_types=1);
$GLOBALS['artful_route_name']='contact';
require_once __DIR__.'/includes/site.php';
if(empty($_SESSION['artful_csrf']))$_SESSION['artful_csrf']=bin2hex(random_bytes(32));
$a=random_int(2,9);$b=random_int(1,6);$_SESSION['captcha']=$a+$b;
$allowed=['presse','conference','partenariat','mission','formation','autre'];$selected=in_array($_GET['motif']??'',$allowed,true)?$_GET['motif']:'';
$meta=artful_page_meta(['title'=>(string)t('contact.title'),'description'=>(string)t('contact.description')]);
?><!doctype html><html lang="<?= artful_locale() ?>"><head><?php artful_render_head($meta); ?></head><body><?php require __DIR__.'/includes/header.php'; ?><main id="main-content"><header class="page-hero"><div class="site-shell"><h1><?= artful_e((string)t('contact.heading')) ?></h1><p><?= artful_e((string)t('contact.lead')) ?></p></div></header><section class="section section--surface"><div class="site-shell contact-layout"><aside><h2><?= artful_e((string)t('contact.entries')) ?></h2><p>Press · Conference · Partnership · Digital project</p><p><a href="mailto:contact@artfulbatinacreativestudios.fr">contact@artfulbatinacreativestudios.fr</a></p></aside><form id="contact-form" class="form-card" action="/contact_handler.php" method="post"><input type="hidden" name="csrf_token" value="<?= artful_e($_SESSION['artful_csrf']) ?>"><input type="hidden" name="lang" value="<?= artful_locale() ?>"><div class="honeypot"><input name="website" tabindex="-1" autocomplete="off"></div>
<div class="field"><label for="motif"><?= artful_e((string)t('contact.labels.type')) ?> *</label><select id="motif" name="motif" required><option value=""><?= artful_e((string)t('contact.labels.choose')) ?></option><?php foreach((array)t('contact.types') as $v=>$l): ?><option value="<?= artful_e($v) ?>"<?= $selected===$v?' selected':'' ?>><?= artful_e((string)$l) ?></option><?php endforeach; ?></select></div>
<div class="grid grid-2"><div class="field"><label for="name"><?= artful_e((string)t('contact.labels.name')) ?> *</label><input id="name" name="name" required maxlength="120"></div><div class="field"><label for="organisation"><?= artful_e((string)t('contact.labels.organisation')) ?></label><input id="organisation" name="organisation" maxlength="160"></div></div>
<div class="grid grid-2"><div class="field"><label for="email"><?= artful_e((string)t('contact.labels.email')) ?> *</label><input id="email" name="email" type="email" required maxlength="190"></div><div class="field"><label for="phone"><?= artful_e((string)t('contact.labels.phone')) ?></label><input id="phone" name="phone" type="tel" maxlength="40"></div></div>
<div class="field"><label for="subject"><?= artful_e((string)t('contact.labels.subject')) ?> *</label><input id="subject" name="subject" required maxlength="180"></div><div class="field"><label for="message"><?= artful_e((string)t('contact.labels.message')) ?> *</label><textarea id="message" name="message" required maxlength="4000"></textarea></div>
<div class="field"><label for="captcha"><?= $a ?> + <?= $b ?> = ? *</label><input id="captcha" name="captcha" required inputmode="numeric"></div><div class="field"><label><input type="checkbox" name="rgpd" value="1" required> <?= artful_e((string)t('contact.labels.consent')) ?></label></div><div id="form-status" class="form-status" aria-live="polite"></div><button class="button button-primary" type="submit"><?= artful_e((string)t('contact.labels.send')) ?></button></form></div></section></main><?php require __DIR__.'/includes/footer.php'; ?>
<script>document.getElementById('contact-form').addEventListener('submit',async function(e){e.preventDefault();const s=document.getElementById('form-status'),b=this.querySelector('button');s.className='form-status is-visible';s.textContent=<?= json_encode(t('contact.sending'),JSON_UNESCAPED_UNICODE) ?>;b.disabled=true;try{const r=await fetch(this.action,{method:'POST',body:new FormData(this),headers:{'X-Requested-With':'XMLHttpRequest'}}),d=await r.json();if(!r.ok||!d.success)throw new Error((d.errors||[]).join(' ')||<?= json_encode(t('contact.error'),JSON_UNESCAPED_UNICODE) ?>);s.className='form-status is-visible is-success';s.textContent=d.message;this.reset()}catch(x){s.className='form-status is-visible is-error';s.textContent=x.message}finally{b.disabled=false}});</script></body></html>
